development:
  adapter: postgresql
  encoding: unicode
  database: the_buzziest_development
  pool: 5
  username: CodyD
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: the_buzziest_test
  pool: 5
  username: CodyD
  password:
