# production:
#   solr:
#     hostname: ec2-50-19-184-22.compute-1.amazonaws.com
#     port: 8983
#     log_level: INFO
#     path: /solr/collection1

# development:
#   solr:
#     hostname: localhost
#     port: 8982
#     log_level: INFO

# test:
#   solr:
#     hostname: localhost
#     port: 8981
#     log_level: WARNING