production:
  solr:
    hostname: ec2-54-242-28-35.compute-1.amazonaws.com
    port: 8983
    log_level: INFO
    path: /solr/the_buzziest_staging
    
development:
  solr:
    hostname: ec2-54-242-28-35.compute-1.amazonaws.com
    port: 8983
    log_level: INFO
    path: /solr/the_buzziest_local

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING